apiVersion: v1
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: "OCP Prometheus"
        type: prometheus
        access: proxy
        url: http://prometheus-operated-monitoring.apps.9.37.135.153.nip.io
        basicAuth: false
        withCredentials: false
        isDefault: true
        jsonData:
            tlsSkipVerify: true
            "httpHeaderName1": "Authorization"
        secureJsonData:
            "httpHeaderValue1": "Bearer \[grafana-ocp token\]"
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana